
default: &default
  adapter: postgresql
  encoding: unicode

  host: localhost
  port: 5432

development:
  <<: *default
  database: estoque_on_rails_dev
  username: <%= ENV["POSTGRES_USER"] %>
  password: 123

